version: "2.4"
services:
  pet-club:
    build: PetClub
    ports:
      - 127.0.0.1:18080:8080
  pet-club-auth:
    build: PetClubAuth
    ports:
      - 127.0.0.1:28080:8080
  ingress-nginx:
    build: IngressNginx
    ports:
      - 127.0.0.1:38080:80

