version: "2.4"
services:
  pet-club:
    build: pet-club
    ports:
      - 127.0.0.1:18080:8080
  pet-club-auth:
    build: pet-club-auth
    ports:
      - 127.0.0.1:28080:8080
  ingress-nginx:
    build: ingress-nginx
    ports:
      - 127.0.0.1:38080:80

