
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    sqlScriptEncoding: UTF-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    ROOT: INFO

cxf:
  path: /club/ws
  servlet:
    init:
      use-x-forwarded-headers: 'true'
